service: dynamo-local

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    TableName: ${self:custom.tableName}

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  tableName: dynamodb-locally
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: dynamodbMigrations
functions:
  create:
    handler: handler.create
    events:
      - http:
          path: create
          method: post
          cors: true

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: attr_1
            AttributeType: S
        KeySchema:
          - AttributeName: attr_1
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
